# Generated by Django 5.2.11 on 2026-03-23 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Karvonsaroy Mahallasi')),
                ('votes_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('age', models.IntegerField()),
                ('is_voted', models.BooleanField(default=False)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BMK.neighborhood')),
            ],
        ),
    ]
