# Generated by Django 5.2.12 on 2026-04-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMK', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='project_id',
            field=models.CharField(default='000000', max_length=20, verbose_name='Loyiha ID raqami'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Mahalla nomi'),
        ),
    ]
