# Generated by Django 5.2.12 on 2026-04-16 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMK', '0005_neighborhood_project_id_alter_neighborhood_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BMK.neighborhood'),
        ),
    ]
