# Generated by Django 5.2.12 on 2026-04-16 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMK', '0006_userprofile_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_votes', to='BMK.userprofile'),
            preserve_default=False,
        ),
    ]
